# 15.What is the total revenue generated by each segment?

SELECT segment, SUM(sale_price * quantity) AS total_revenue
FROM order_details
JOIN product_details ON order_details.order_id = product_details.order_id
GROUP BY segment;