# 19.What is the total profit generated by each state?

SELECT state, SUM(profit) AS total_profit
FROM order_details
JOIN product_details ON order_details.order_id = product_details.order_id
GROUP BY state;